import re
from typing import Dict, List, Optional
import logging

from logging_setup import get_logger


class PlanParser:
    """
    Parse structured plans generated by the AI.
    Extract fields:
    - Goal
    - Task Type
    - Steps
    - Recommended Agent
    - Tools Required
    - Approval Required

    Return structured dictionary.
    """

    def __init__(self):
        self.logger = get_logger(__name__)

    def parse_plan(self, plan_content: str) -> Optional[Dict]:
        """
        Parse a plan and extract structured information.

        Args:
            plan_content: String content of the plan

        Returns:
            Dictionary with parsed plan information, or None if parsing fails
        """
        logger = self.logger

        try:
            # Initialize result dictionary
            parsed_plan = {
                'goal': '',
                'task_type': '',
                'steps': [],
                'recommended_agent': '',
                'tools_required': [],
                'approval_required': True,
                'raw_content': plan_content
            }

            # Extract goal (usually in first heading or first paragraph after metadata)
            goal_match = re.search(r'#\s+(.+?)(?:\n|$)|##\s+(.+?)(?:\n|$)', plan_content)
            if goal_match:
                parsed_plan['goal'] = (goal_match.group(1) or goal_match.group(2)).strip()

            # Look for more specific goal indicators
            goal_patterns = [
                r'Goal:\s*(.+?)(?:\n|$)',
                r'Objective:\s*(.+?)(?:\n|$)',
                r'Purpose:\s*(.+?)(?:\n|$)'
            ]

            for pattern in goal_patterns:
                goal_match = re.search(pattern, plan_content, re.IGNORECASE)
                if goal_match:
                    parsed_plan['goal'] = goal_match.group(1).strip()
                    break

            # Extract task type
            task_type_patterns = [
                r'Task Type:\s*(.+?)(?:\n|$)',
                r'Type:\s*(.+?)(?:\n|$)',
                r'Category:\s*(.+?)(?:\n|$)'
            ]

            for pattern in task_type_patterns:
                task_type_match = re.search(pattern, plan_content, re.IGNORECASE)
                if task_type_match:
                    parsed_plan['task_type'] = task_type_match.group(1).strip()
                    break

            # Extract recommended agent
            agent_patterns = [
                r'Recommended Agent:\s*(.+?)(?:\n|$)',
                r'Agent:\s*(.+?)(?:\n|$)',
                r'Assigned To:\s*(.+?)(?:\n|$)'
            ]

            for pattern in agent_patterns:
                agent_match = re.search(pattern, plan_content, re.IGNORECASE)
                if agent_match:
                    parsed_plan['recommended_agent'] = agent_match.group(1).strip()
                    break

            # Extract tools required (as a list)
            tools_match = re.search(r'Tools Required:(.*?)(?:\n\n|\n[A-Z][a-z]+:|$)', plan_content, re.DOTALL | re.IGNORECASE)
            if tools_match:
                tools_text = tools_match.group(1).strip()
                # Split by lines or commas to get individual tools
                tools_list = [tool.strip().strip('-').strip('*').strip() for tool in re.split(r'\n|,', tools_text) if tool.strip()]
                parsed_plan['tools_required'] = tools_list

            # Alternative way to find tools
            if not parsed_plan['tools_required']:
                # Look for bullet points after "Tools Required" or similar
                tools_alt_match = re.search(r'(?:tools required|using|requires):\s*(.+?)(?:\n\n|\n[A-Z][a-z]+:|$)', plan_content, re.DOTALL | re.IGNORECASE)
                if tools_alt_match:
                    tools_text = tools_alt_match.group(1).strip()
                    tools_list = [tool.strip().strip('-').strip('*').strip() for tool in re.split(r'\n|,', tools_text) if tool.strip()]
                    parsed_plan['tools_required'] = tools_list

            # Extract steps (usually numbered lists or bullet points)
            # Look for sections that indicate steps
            steps_patterns = [
                r'Steps:(.*?)(?:\n\n[A-Z][a-z]+:|\Z)',
                r'Procedure:(.*?)(?:\n\n[A-Z][a-z]+:|\Z)',
                r'Process:(.*?)(?:\n\n[A-Z][a-z]+:|\Z)',
                r'Action Items:(.*?)(?:\n\n[A-Z][a-z]+:|\Z)',
                r'(?:To achieve this|Next,|Then,|First,|Second,|Finally,).*?(?:\n\n[A-Z][a-z]+:|\Z)'
            ]

            for pattern in steps_patterns:
                steps_match = re.search(pattern, plan_content, re.DOTALL | re.IGNORECASE)
                if steps_match:
                    steps_text = steps_match.group(1).strip()

                    # Extract individual steps (numbered or bulleted)
                    step_lines = steps_text.split('\n')
                    steps = []

                    for line in step_lines:
                        line = line.strip()
                        if line and (line.startswith(('1.', '2.', '3.', '4.', '5.', '-', '*', '•')) or
                                   re.match(r'^\d+\.', line) or
                                   re.match(r'^[a-zA-Z]\.', line)):
                            # Clean up the step
                            step = re.sub(r'^[\d\-*•]+[.\s]*', '', line).strip()
                            if step:
                                steps.append(step)

                    if steps:
                        parsed_plan['steps'] = steps
                        break

            # If no steps were found in the structured way, try to extract any list-like items
            if not parsed_plan['steps']:
                # Look for any numbered or bulleted items in the entire content
                potential_steps = []
                lines = plan_content.split('\n')

                for line in lines:
                    line = line.strip()
                    if (line.startswith(('1.', '2.', '3.', '4.', '5.', '-', '*', '•')) or
                        re.match(r'^\d+\.', line) or
                        re.match(r'^[a-zA-Z]\.', line)):

                        step = re.sub(r'^[\d\-*•]+[.\s]*', '', line).strip()
                        if step and len(step) > 5:  # Avoid very short items
                            potential_steps.append(step)

                parsed_plan['steps'] = potential_steps[:10]  # Limit to first 10 steps to avoid noise

            # Determine if approval is required (by default yes, unless explicitly stated otherwise)
            approval_match = re.search(r'Approval Required:\s*(no|false|0)', plan_content, re.IGNORECASE)
            if approval_match:
                parsed_plan['approval_required'] = False
            else:
                # Look for auto-approve indicators
                auto_approve_indicators = [
                    r'automatic execution',
                    r'auto-execute',
                    r'no approval needed',
                    r'direct execution'
                ]

                for indicator in auto_approve_indicators:
                    if re.search(indicator, plan_content, re.IGNORECASE):
                        parsed_plan['approval_required'] = False
                        break

            logger.info(f"Parsed plan with goal: {parsed_plan['goal'][:50]}..." if parsed_plan['goal'] else "Parsed plan with no clear goal")
            return parsed_plan

        except Exception as e:
            logger.error(f"Error parsing plan: {str(e)}")
            return None


def parse_plan(plan_content: str) -> Optional[Dict]:
    """
    Standalone function to parse a plan.
    """
    parser = PlanParser()
    return parser.parse_plan(plan_content)